import { readFileSync, existsSync } from "fs";
import { join } from "path";
import type { DashboardData } from "./types";

// In-memory cache
let cache: { data: DashboardData; ts: number } | null = null;
const CACHE_TTL_MS = 30 * 1000; // 30 seconds (file is static, just avoid re-reads)

const EMPTY_DATA: DashboardData = {
  brackets: [],
  picks: [],
  games: [],
  teams: [],
  snapshots: [],
  meta: { last_updated: "", last_checked_at: 0, current_round: "R64", games_completed: 0 },
};

/**
 * Load dashboard data from the static JSON file generated by the scraper.
 * No Google Sheets API calls — the scraper writes to Sheets AND exports
 * public/data.json for the frontend to consume.
 */
export async function fetchDashboardData(): Promise<DashboardData> {
  if (cache && Date.now() - cache.ts < CACHE_TTL_MS) {
    return cache.data;
  }

  try {
    // Try multiple locations for the data file
    const candidates = [
      join(process.cwd(), "public", "data.json"),
      join(process.cwd(), "data.json"),
    ];

    // Also check backup locations
    const backupCandidates = [
      join(process.cwd(), "public", "data.backup.json"),
      join(process.cwd(), "data.backup.json"),
    ];

    let raw: string | null = null;
    for (const path of candidates) {
      if (existsSync(path)) {
        raw = readFileSync(path, "utf8");
        break;
      }
    }

    // Fallback to backup if primary not found
    if (!raw) {
      for (const path of backupCandidates) {
        if (existsSync(path)) {
          console.warn("data.json not found, using backup");
          raw = readFileSync(path, "utf8");
          break;
        }
      }
    }

    if (!raw) {
      console.error("No data.json or backup found. Run the scraper first.");
      return EMPTY_DATA;
    }

    const data: DashboardData = JSON.parse(raw);
    cache = { data, ts: Date.now() };
    return data;
  } catch (error) {
    console.error("Failed to load dashboard data:", error);
    return EMPTY_DATA;
  }
}
